services:
  server:
    container_name: code-sync-server
    build:
      context: ./server
      dockerfile: Dockerfile
    deploy:
      resources:
        limits:
          memory: 512M
    networks:
      - Code-Sync
    ports:
      - "3000:3000"

  client:
    container_name: code-sync-client
    build:
      context: ./client
      dockerfile: Dockerfile
    deploy:
      resources:
        limits:
          memory: 512M
    
    networks:
      - Code-Sync
    ports:
      - "5173:80"
    depends_on:
      - server

networks:
  Code-Sync:
    driver: bridge